# Generated by Django 4.0.4 on 2022-05-15 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('name', models.CharField(default='default', max_length=200, primary_key=True, serialize=False)),
                ('size', models.CharField(default='0', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inv_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField(null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Logi_App', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Logi_App.warehouse')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
