# Generated by Django 4.0.4 on 2022-05-15 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Logi_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_item',
            name='warehouse',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Logi_App.warehouse'),
        ),
    ]
