# Generated by Django 4.0.4 on 2022-05-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logi_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inv_item',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='inv_item',
            old_name='published',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='inv_item',
            old_name='excerpt',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='inv_item',
            old_name='author',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='inv_item',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='state',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
